#!/bin/sh

printf "Xvfb|%s\n" "$*" >> "$ROONSCAPE_CAPTURE_TEST_PROCESS_LOG"
# Emulate the displayfd readiness report, without touching real X sockets.
printf "999\n"
stopped=0

stop() {
  [ "$stopped" -eq 1 ] && return
  stopped=1
  printf "Xvfb-stopped\n" >> "$ROONSCAPE_CAPTURE_TEST_PROCESS_LOG"
}

trap 'stop; exit 0' TERM INT EXIT
while :; do /usr/bin/sleep 0.05; done
